// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetAdoption.Models;

namespace PetAdoption.Migrations
{
    [DbContext(typeof(PetAdoptionContextDB))]
    [Migration("20200203010143_InitialDataBase")]
    partial class InitialDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PetAdoption.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("CustBalance");

                    b.Property<string>("CustName");

                    b.Property<string>("CustPhone");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PetAdoption.Models.CustomerPet", b =>
                {
                    b.Property<int>("CustomerPetId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CustomerId");

                    b.Property<int>("PetId");

                    b.HasKey("CustomerPetId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PetId");

                    b.ToTable("CustomerPets");
                });

            modelBuilder.Entity("PetAdoption.Models.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("PetDateArrived");

                    b.Property<string>("PetName");

                    b.HasKey("PetId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("PetAdoption.Models.CustomerPet", b =>
                {
                    b.HasOne("PetAdoption.Models.Customer", "Customer")
                        .WithMany("Pets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PetAdoption.Models.Pet", "Pet")
                        .WithMany("Customers")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
